export interface CsvRecord {
    [index:string]: string|number,
}

export interface DatabaseRecord {
    [index:string]: string|number,
}

export interface OotpExportDataColumn {
    nameInSource: string,
    databaseColumnName: string,
    type: OotpExportDataColumnType,
}

export type OotpExportDataColumnType = "INTEGER"|"REAL"|"TEXT"|"DATETIME"

export interface DataTableColumn {
    name: string,
    type: OotpExportDataColumnType,
    notNull: boolean,
}

export interface Constraint {
    type: "UNIQUE"
    fields: string[],
}

export interface DatatableModel {
    tableName: string,
    columns: DataTableColumn[],
    primaryKey?: PrimaryKey,
    constraints?: Constraint[],
    foreignKeyTables?: string[],
    indicies?: Index[],
}

export interface Index {
    columns: string[],
}

export interface PrimaryKey {
    column: string,
    autoincrement: boolean,
}

export interface PtCard {
    CardID:number,
    CardTitle:string,
    CardValue:number,
    CardType:number,
    CardSubType:number,
    CardBadge:string,
    CardSeries:string,
    Year:number,
    Peak:string,
    Team:string,
    Franchise:string,
    FirstName:string,
    LastName:string,
    NickName:string,
    UniformNumber:number,
    DayOB:number,
    MonthOB:number,
    YearOB:number,
    Bats:number,
    Throws:number,
    Position:number,
    PitcherRole:number,
    Contact:number,
    Gap:number,
    Power:number,
    Eye:number,
    AvoidKs:number,
    BABIP:number,
    ContactvL:number,
    GapvL:number,
    PowervL:number,
    EyevL:number,
    AvoidKvL:number,
    BABIPvL:number,
    ContactvR:number,
    GapvR:number,
    PowervR:number,
    EyevR:number,
    AvoidKvR:number,
    BABIPvR:number,
    GBHitterType:number,
    FBHitterType:number,
    BattedBallType:number,
    Speed:number,
    StealRate:number,
    Stealing:number,
    Baserunning:number,
    Sacbunt:number,
    Buntforhit:number,
    Stuff:number,
    Movement:number,
    Control:number,
    pHR:number,
    pBABIP:number,
    StuffvL:number,
    MovementvL:number,
    ControlvL:number,
    pHRvL:number,
    pBABIPvL:number,
    StuffvR:number,
    MovementvR:number,
    ControlvR:number,
    pHRvR:number,
    pBABIPvR:number,
    Fastball:number,
    Slider:number,
    Curveball:number,
    Changeup:number,
    Cutter:number,
    Sinker:number,
    Splitter:number,
    Forkball:number,
    Screwball:number,
    Circlechange:number,
    Knucklecurve:number,
    Knuckleball:number,
    Stamina:number,
    Hold:number,
    GB:number,
    Velocity:number,
    ArmSlot:number,
    Height:number,
    InfieldRange:number,
    InfieldError:number,
    InfieldArm:number,
    DP:number,
    CatcherAbil:number,
    CatcherFrame:number,
    CatcherArm:number,
    OFRange:number,
    OFError:number,
    OFArm:number,
    PosRatingP:number,
    PosRatingC:number,
    PosRating1B:number,
    PosRating2B:number,
    PosRating3B:number,
    PosRatingSS:number,
    PosRatingLF:number,
    PosRatingCF:number,
    PosRatingRF:number,
    LearnC:number,
    Learn1B:number,
    Learn2B:number,
    Learn3B:number,
    LearnSS:number,
    LearnLF:number,
    LearnCF:number,
    LearnRF:number,
    era:number,
    MissionValue:number,
    limit:number,
    owned:number,
    brefid:string,
    date:number,
    LiveUpdateID:number,
    PtCardID:number,
}

export interface BattingStats {
    PtCardID: number,
    G: number, 
    GS: number, 
    PA: number,
    AB: number,
    H: number,
    '1B': number, 
    '2B': number, 
    '3B': number, 
    HR: number, 
    RBI: number, 
    R: number, 
    BB: number, 
    'BB%': number, 
    IBB: number, 
    HP: number, 
    SH: number,
    SF: number, 
    CI: number, 
    SO: number, 
    'SO%': number, 
    GIDP: number, 
    EBH: number, 
    TB: number, 
    AVG: number, 
    OBP: number, 
    SLG: number, 
    RC: number, 
    'RC/27': number, 
    ISO: number, 
    wOBA: number, 
    OPS: number, 
    'OPS+': number,
    BABIP: number, 
    WPA: number, 
    wRC: number, 
    'wRC+': number, 
    wRAA: number, 
    WAR: number, 
    'PI/PA': number, 
    SB: number, 
    CS: number, 
    'SB%': number, 
    BatR: number, 
    wSB: number, 
    UBR: number, 
    BsR: number,
}

export interface PitchingStats {
    PtCardID: number,
    G: number,
    GS: number,
    W: number,
    L: number,
    "WIN%": number,
    SVO: number,
    SV: number,
    "SV%": number,
    BS: number,
    "BS%": number,
    HLD: number,
    SD: number,
    MD: number,
    IP: number,
    BF: number,
    AB: number,
    HA: number,
    "1B": number,
    "2B": number,
    "3B": number,
    HR: number,
    TB: number,
    R: number,
    ER: number,
    BB: number,
    IBB: number,
    K: number,
    HP: number,
    ERA: number,
    AVG: number,
    OBP: number,
    SLG: number,
    OPS: number,
    BABIP: number,
    WHIP: number,
    "BRA/9": number,
    "HR/9": number,
    "H/9": number,
    "BB/9": number,
    "K/9": number,
    "K/BB": number,
    "K%": number,
    "BB%": number,
    "K%-BB%": number,
    SH: number,
    SF: number,
    WP: number,
    BK: number,
    CI: number,
    DP: number,
    RA: number,
    GF: number,
    IR: number,
    IRS: number,
    "IRS%": number,
    "LOB%": number,
    pLi: number,
    "GF%": number,
    QS: number,
    "QS%": number,
    CG: number,
    "CG%": number,
    SHO: number,
    PPG: number,
    RS: number,
    RSG: number,
    PI: number,
    GB: number,
    FB: number,
    "GO%": number,
    SB: number,
    CS: number,
    "ERA+": number,
    FIP: number,
    "FIP-": number,
    WPA: number,
    WAR: number,
    rWAR: number,
    SIERA: number,
    Outs: number,
}


export interface LeaguePlayStats {
    LeagueYear: number,
}

export type BattingStatsExpanded = BattingStats & Partial<PtCard> & Partial<LeaguePlayStats>
export type PitchingStatsExpanded = PitchingStats & Partial<PtCard> & Partial<LeaguePlayStats>

export enum Bats {
    R = 1,
    L = 2,
    S = 3,
}

export enum Throws {
    R = 1,
    L = 2,
}

export enum Position {
    P = 1,
    C = 2,
    '1B' = 3,
    '2B' = 4,
    '3B' = 5,
    SS = 6,
    LF = 7,
    CF = 8,
    RF = 9,
    DH = 10,
}

export interface GeneralStatsWriteFilter {
    TeamName: string,
}

export interface LiveUpdate {
    LiveUpdateID: number | null,
    EffectiveDate: string,
}